#define  IDENTIFIER 1
#define CONSTANT 2
#define STRING_LITERAL 3
#define SIZEOF 4
#define PTR_OP 5
#define INC_OP 6
#define DEC_OP 7
#define LEFT_OP  8
#define RIGHT_OP 9
#define LE_OP 10
#define GE_OP 11 
#define EQ_OP 12
#define NE_OP 13
#define AND_OP 14 
#define OR_OP 15
#define MUL_ASSIGN 16
#define DIV_ASSIGN 17
#define MOD_ASSIGN 18
#define ADD_ASSIGN 19
#define SUB_ASSIGN 20
#define LEFT_ASSIGN 21 
#define RIGHT_ASSIGN 22
#define AND_ASSIGN 23
#define XOR_ASSIGN 24
#define OR_ASSIGN 25
#define TYPE_NAME 26
#define TYPEDEF 27
#define EXTERN 28
#define STATIC 29
#define AUTO 30
#define REGISTER 31
#define CHAR 32
#define SHORT 33
#define INT 34
#define LONG 35
#define UNSIGNED 36
#define FLOAT 37
#define DOUBLE 38
#define CONST 39
#define  VOLATILE 40
#define VOID 41
#define STRUCT 42
#define UNION 43
#define ENUM 44
#define ELLIPSIS 45
#define CASE 46
#define DEFAULT 47
#define IF 48
#define ELSE 49
#define SWITCH 50
#define WHILE 51
#define DO 52
#define FOR 53
#define GOTO 54
#define CONTINUE 55
#define BREAK 56
#define RETURN 57